-- COMMENTS DML

-- INSERT (COMMENT_ID 使用序列 SEQ_COMMENTS 生成)
INSERT INTO COMMENTS (USER_ID, POST_ID, CONTENT)
VALUES ( 1, 1, 'Great post!');

-- SELECT
SELECT * FROM COMMENTS
WHERE COMMENT_ID = 1;

-- UPDATE
UPDATE COMMENTS
SET CONTENT = 'Updated comment content.'
WHERE COMMENT_ID = 1;

-- DELETE
DELETE FROM COMMENTS
WHERE COMMENT_ID = 1;

COMMIT;