-- POSTS DML

-- INSERT
INSERT INTO POSTS (POST_ID, USER_ID, CONTENT)
VALUES (1, 1, 'First post from Steven.');

-- SELECT
SELECT * FROM POSTS WHERE POST_ID = 1;

-- UPDATE
UPDATE POSTS SET CONTENT = 'Updated post content.' WHERE POST_ID = 1;

-- DELETE
DELETE FROM POSTS WHERE POST_ID = 1;