-- USERS DML

-- INSERT (USER_ID 使用序列 SEQ_USERS 生成)
INSERT INTO USERS (USER_NAME, EMAIL, PASSWORD, BIOGRAPHY)
VALUES ('Steven', 'steven@example.com', 'hashed_password_1', 'Software Developer');

-- SELECT
SELECT * FROM USERS
WHERE USER_ID = 1;

-- UPDATE
UPDATE USERS
SET BIOGRAPHY = 'Senior Software Developer'
WHERE USER_ID = 1;

-- DELETE
DELETE FROM USERS
WHERE USER_ID = 1;