-- COMMENTS DML

-- INSERT
INSERT INTO COMMENTS (COMMENT_ID, USER_ID, POST_ID, CONTENT)
VALUES (1, 1, 1, 'Great post!');

-- SELECT
SELECT * FROM COMMENTS WHERE COMMENT_ID = 1;

-- UPDATE
UPDATE COMMENTS SET CONTENT = 'Updated comment content.' WHERE COMMENT_ID = 1;

-- DELETE
DELETE FROM COMMENTS WHERE COMMENT_ID = 1;